#pragma once

// The "sensor bridge" layer connects UAVCAN sensor messages to PX4’s internal uORB topics.
#include "sensor_bridge.hpp"
// Autogenerated C++ type for the UAVCAN message uavcan.equipment.power.CircuitStatus
#include <uavcan/equipment/power/CircuitStatus.hpp>
// Autogenerated from msg/circuit_status.msg – defines struct circuit_status_s and ORB_ID(circuit_status)
#include <uORB/topics/circuit_status.h>

class UavcanCircuitStatusBridge : public UavcanSensorBridgeBase
{
public:
	static const char *const NAME;

	// Constructor: PX4 passes the UAVCAN node handle here
	UavcanCircuitStatusBridge(uavcan::INode &node);

	const char *get_name() const override { return NAME; }

	// Called once when the bridge starts up to register the UAVCAN subscriber
	int init() override;

private:
	/**
	 * @brief UAVCAN subscription callback.
	 * Runs every time a CircuitStatus message is received on the CAN bus.
	 * Converts the UAVCAN message into PX4’s uORB format (circuit_status_s)
	 * and publishes it so the rest of PX4 can use it.
	 */
	void circuit_status_sub_cb(const uavcan::ReceivedDataStructure<uavcan::equipment::power::CircuitStatus> &msg);

	// MethodBinder tells libuavcan how to call a class member as a callback.
	// It stores both the object pointer and the member-function pointer.
	typedef uavcan::MethodBinder<UavcanCircuitStatusBridge *,
		void (UavcanCircuitStatusBridge::*)
		(const uavcan::ReceivedDataStructure<uavcan::equipment::power::CircuitStatus> &) >
		CircuitStatusInfoCbBinder;

	// The actual UAVCAN subscriber object that listens for CircuitStatus messages
	uavcan::Subscriber<uavcan::equipment::power::CircuitStatus, CircuitStatusInfoCbBinder> _sub_circuit_status;
};
